#!/usr/bin/env bash

# Check for `deno` in PATH
if ! command -v deno &> /dev/null ; then
    printf "(\e[31mError\e[0m): Deno is not found in your PATH enviroment\n"
    printf "(\e[31mError\e[0m): Make sure you've installed it and set in properly\n"
    printf "(\e[31mError\e[0m): Try again later\n"

    printf "(\e[31mError\e[0m): Aborting request..."
    exit
fi

# Check for `./target` directory
if test -d ./target ; then
    rm -r -f ./target/*
else
    mkdir target
fi

# Build the project
deno compile -q -A -o target/keiryo src/index.ts

# Check the build status
if test -f ./target/keiryo ; then
    printf "(\e[32mInfo\e[0m): Build complete\n"
    printf "(\e[32mInfo\e[0m): Run './target/keiryo --help' to verify\n"
    exit
fi