/* Operators */
export const operator = new Map([
    ['~', 'Tilde'],
    ['!', 'Not']
    ['@', 'At']
    ['$', 'Dollar']
    ['%', 'Percent']
    ['^', 'Caret']
    ['&', 'And']
    ['*', 'Star']
    ['(', 'ParenL']
    [')', 'ParenR']
    ['{', 'CurlyL']
    ['}', 'CurlyR']
    ['[', 'SquareL']
    [']', 'SquareR']
    ['|', 'Pipe']
    [':', 'Colon']
    [';', 'Semi']
    ['<', 'Less']
    ['>', 'More']
    [',', 'Comma']
    ['.', 'Dot']
    ['?', 'Question']
    ['/', 'SlashF']
]);